apiVersion: v1
name: lightstep
version: 1.2.2
appVersion: "2021-01-26_23-02-36Z"
description: Lightstep satellite to collect telemetry data.
home: https://lightstep.com/
icon: https://go.lightstep.com/rs/260-KGM-472/images/logo-medium-color-400x100.jpg
engine: gotpl
